import { User, Equipment, Order, DashboardStats } from '@/types';

export const mockUsers: User[] = [
  {
    id: '1',
    email: 'admin@university.edu',
    name: 'Dr. Sarah Mitchell',
    role: 'admin',
    department: 'IT Administration',
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    email: 'procurement@university.edu',
    name: 'Michael Chen',
    role: 'procurement_manager',
    department: 'Procurement Office',
    createdAt: '2024-02-01',
  },
  {
    id: '3',
    email: 'employee@university.edu',
    name: 'Emily Johnson',
    role: 'employee',
    department: 'Computer Science',
    createdAt: '2024-03-10',
  },
  {
    id: '4',
    email: 'professor@university.edu',
    name: 'Dr. James Wilson',
    role: 'employee',
    department: 'Engineering',
    createdAt: '2024-03-15',
  },
  {
    id: '5',
    email: 'researcher@university.edu',
    name: 'Dr. Lisa Park',
    role: 'employee',
    department: 'Physics',
    createdAt: '2024-04-01',
  },
];

export const mockEquipment: Equipment[] = [
  {
    id: '1',
    name: 'Dell XPS 15 Laptop',
    category: 'Laptops',
    description: 'High-performance laptop for research and development',
    specifications: 'Intel i7-13700H, 32GB RAM, 1TB SSD, RTX 4060',
    unitPrice: 1899.99,
    imageUrl: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400',
    inStock: true,
    stockQuantity: 15,
  },
  {
    id: '2',
    name: 'Apple MacBook Pro 16"',
    category: 'Laptops',
    description: 'Professional laptop for creative and technical work',
    specifications: 'M3 Pro, 36GB RAM, 1TB SSD',
    unitPrice: 2999.99,
    imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400',
    inStock: true,
    stockQuantity: 8,
  },
  {
    id: '3',
    name: 'Dell UltraSharp 27" 4K Monitor',
    category: 'Monitors',
    description: 'Professional-grade 4K monitor with accurate colors',
    specifications: '27" IPS, 4K UHD, USB-C, 99% sRGB',
    unitPrice: 649.99,
    imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400',
    inStock: true,
    stockQuantity: 25,
  },
  {
    id: '4',
    name: 'Logitech MX Master 3S Mouse',
    category: 'Peripherals',
    description: 'Advanced wireless mouse for productivity',
    specifications: 'Bluetooth, USB-C charging, 8K DPI',
    unitPrice: 99.99,
    imageUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400',
    inStock: true,
    stockQuantity: 50,
  },
  {
    id: '5',
    name: 'HP LaserJet Pro MFP',
    category: 'Printers',
    description: 'Multifunction laser printer for office use',
    specifications: 'Print/Scan/Copy, 40ppm, WiFi',
    unitPrice: 449.99,
    imageUrl: 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=400',
    inStock: true,
    stockQuantity: 10,
  },
  {
    id: '6',
    name: 'NVIDIA RTX 4090 GPU',
    category: 'Components',
    description: 'High-end graphics card for AI/ML research',
    specifications: '24GB GDDR6X, CUDA Cores: 16384',
    unitPrice: 1599.99,
    imageUrl: 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=400',
    inStock: false,
    stockQuantity: 0,
  },
  {
    id: '7',
    name: 'Synology NAS DS923+',
    category: 'Storage',
    description: '4-bay NAS for data storage and backup',
    specifications: '4-bay, AMD Ryzen, 4GB RAM expandable',
    unitPrice: 599.99,
    imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400',
    inStock: true,
    stockQuantity: 5,
  },
  {
    id: '8',
    name: 'Mechanical Keyboard - Keychron Q1',
    category: 'Peripherals',
    description: 'Premium mechanical keyboard for typing comfort',
    specifications: 'Hot-swappable, QMK/VIA, Aluminum',
    unitPrice: 179.99,
    imageUrl: 'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=400',
    inStock: true,
    stockQuantity: 30,
  },
];

export const mockOrders: Order[] = [
  {
    id: 'ORD-001',
    userId: '3',
    userName: 'Emily Johnson',
    department: 'Computer Science',
    items: [
      {
        equipmentId: '1',
        equipment: mockEquipment[0],
        quantity: 2,
        unitPrice: 1899.99,
      },
      {
        equipmentId: '3',
        equipment: mockEquipment[2],
        quantity: 2,
        unitPrice: 649.99,
      },
    ],
    totalAmount: 5099.96,
    status: 'pending',
    justification: 'Required for new faculty members joining the department',
    createdAt: '2024-12-10T10:30:00Z',
    updatedAt: '2024-12-10T10:30:00Z',
  },
  {
    id: 'ORD-002',
    userId: '4',
    userName: 'Dr. James Wilson',
    department: 'Engineering',
    items: [
      {
        equipmentId: '6',
        equipment: mockEquipment[5],
        quantity: 1,
        unitPrice: 1599.99,
      },
    ],
    totalAmount: 1599.99,
    status: 'approved',
    justification: 'GPU needed for machine learning research project',
    createdAt: '2024-12-08T14:15:00Z',
    updatedAt: '2024-12-09T09:00:00Z',
  },
  {
    id: 'ORD-003',
    userId: '5',
    userName: 'Dr. Lisa Park',
    department: 'Physics',
    items: [
      {
        equipmentId: '2',
        equipment: mockEquipment[1],
        quantity: 1,
        unitPrice: 2999.99,
      },
      {
        equipmentId: '4',
        equipment: mockEquipment[3],
        quantity: 1,
        unitPrice: 99.99,
      },
    ],
    totalAmount: 3099.98,
    status: 'delivered',
    justification: 'Replacement for outdated equipment',
    createdAt: '2024-12-01T08:00:00Z',
    updatedAt: '2024-12-05T16:30:00Z',
  },
  {
    id: 'ORD-004',
    userId: '3',
    userName: 'Emily Johnson',
    department: 'Computer Science',
    items: [
      {
        equipmentId: '7',
        equipment: mockEquipment[6],
        quantity: 2,
        unitPrice: 599.99,
      },
    ],
    totalAmount: 1199.98,
    status: 'rejected',
    justification: 'Storage expansion for research data',
    createdAt: '2024-11-28T11:45:00Z',
    updatedAt: '2024-11-30T10:00:00Z',
  },
];

export const mockDashboardStats: DashboardStats = {
  totalOrders: 47,
  pendingOrders: 12,
  approvedOrders: 28,
  totalSpent: 125750.00,
  monthlyBudget: 200000.00,
};

export const equipmentCategories = [
  'All',
  'Laptops',
  'Monitors',
  'Peripherals',
  'Printers',
  'Components',
  'Storage',
];
